### ISSUE TITLE
Module build failed: ReferenceError: Symbol is not defined

### ISSUE THREAD

**Issue by whitebook** [mobxjs/mobx-react-boilerplate#12]
ERROR in ./src/index.jsx
Module build failed: ReferenceError: Symbol is not defined
    at plugin (/apps/git/mobx-react-boilerplate/node_modules/react-hot-loader/lib/babel/index.js:53:23)
    at Function.memoisePluginContainer (/apps/git/mobx-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:13)
    at Function.normalisePlugin (/apps/git/mobx-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:141:32)
    at /apps/git/mobx-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:181:30
    at Array.map (native)
    at Function.normalisePlugins (/apps/git/mobx-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/apps/git/mobx-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/apps/git/mobx-react-boilerplate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (/apps/git/mobx-react-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/apps/git/mobx-react-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/apps/git/mobx-react-boilerplate/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/apps/git/mobx-react-boilerplate/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/apps/git/mobx-react-boilerplate/node_modules/babel-loader/index.js:88:12)
 @ multi main

**Comment by mweststrate** [comment]
Which node version?

Op wo 3 aug. 2016 om 21:06 schreef whitebook <notifications@github.com>:

**Comment by whitebook** [comment]
Good Call, didnt notice that...Fixed. Using Node 4.4.7 

Thanks.

**Comment by CharlieIGG** [comment]
Sorry to bump such an old issue, but I'm facing something similar when using mobx in an angular project (with mobx-angular, albeit the TS error points to mobx itself): 

I'm using node v10.13

<img width="603" alt="screen shot 2018-11-26 at 5 20 50 pm" src="https://user-images.githubusercontent.com/14896457/49048248-b2672b80-f19f-11e8-8a45-c6ec0959b5d7.png">

**Comment by mweststrate** [comment]
Note that responding to closed issues is generally pointless, as nobody
will see it, except for people that originally participated in the
discussion. Please open a new issue, and include your project setup

Op di 27 nov. 2018 om 00:21 schreef Carlos I. Garcia <
notifications@github.com>:

**Comment by CharlieIGG** [comment]
Thanks @mweststrate. I found the issue, so for anybody who stumbles upon this: If you're seeing this problem you need to update to Typescript 2.7.0 or above.
