### ISSUE TITLE
Error with events when running

### ISSUE THREAD

**Issue by SteveALee** [mobxjs/mobx-react-boilerplate#5]
with node 4.3.2. (64 bit) I installed and ran I get

<pre>
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
</pre>

**Comment by SteveALee** [comment]
doh! my bad. Somerthing was holding the port open

`listen EADDRINUSE 127.0.0.1:3000`
